import { palette } from '@/providers/ThemeProvider/palette'
import { createGlobalTheme, globalStyle } from '@vanilla-extract/css'

export const vars = createGlobalTheme('[data-theme="light"]', {
  colors: {
    system: {
      red: palette.light.default.red,
      orange: palette.light.default.orange,
      yellow: palette.light.default.yellow,
      green: palette.light.default.green,
      mint: palette.light.default.mint,
      teal: palette.light.default.teal,
      cyan: palette.light.default.cyan,
      blue: palette.light.default.blue,
      indigo: palette.light.default.indigo,
      purple: palette.light.default.purple,
      pink: palette.light.default.pink,
      brown: palette.light.default.brown,
      gray: palette.light.default.gray,
      white: palette.light.default.white,
      black: palette.light.default.black,
    },
    backgrounds: {
      primary: palette.light.default.white,
      secondary: palette.light.default.gray6,
      tertiary: palette.light.default.white,
    },
    groupedBackgrounds: {
      primary: palette.light.default.gray6,
      secondary: palette.light.default.white,
      tertiary: palette.light.default.gray6,
    },
    labels: {
      primary: palette.light.default.black,
      secondary: palette.light.default.labelsSecondary,
      tertiary: palette.light.default.labelsTertiary,
      quarternary: palette.light.default.labelsQuarternary,
    },
    fills: {
      primary: palette.light.default.fillsPrimary,
      secondary: palette.light.default.fillsSecondary,
      tertiary: palette.light.default.fillsTertiary,
      quarternary: palette.light.default.fillsQuarternary,
    },
    separators: {
      opaque: palette.light.default.separatorOpaque,
      nonOpaque: palette.light.default.separatorNonOpaque,
    },
    accents: {
      primary: `hsl(${palette.light.default.majorelleBlue})`,
      primary_a90: `hsl(${palette.light.default.majorelleBlue} / 0.9)`,
      secondary: `hsl(${palette.light.default.terraCotta})`,
      secondary_a90: `hsl(${palette.light.default.terraCotta} / 0.9)`,
    },
  },
})

export const darkVars = createGlobalTheme('[data-theme="dark"]', vars, {
  colors: {
    system: {
      red: palette.dark.default.red,
      orange: palette.dark.default.orange,
      yellow: palette.dark.default.yellow,
      green: palette.dark.default.green,
      mint: palette.dark.default.mint,
      teal: palette.dark.default.teal,
      cyan: palette.dark.default.cyan,
      blue: palette.dark.default.blue,
      indigo: palette.dark.default.indigo,
      purple: palette.dark.default.purple,
      pink: palette.dark.default.pink,
      brown: palette.dark.default.brown,
      gray: palette.dark.default.gray,
      white: palette.dark.default.white,
      black: palette.dark.default.black,
    },
    backgrounds: {
      primary: palette.dark.default.black,
      secondary: palette.dark.default.gray6,
      tertiary: palette.dark.default.gray5,
    },
    groupedBackgrounds: {
      primary: palette.dark.default.black,
      secondary: palette.dark.default.gray6,
      tertiary: palette.dark.default.gray5,
    },
    labels: {
      primary: palette.dark.default.white,
      secondary: palette.dark.default.labelsSecondary,
      tertiary: palette.dark.default.labelsTertiary,
      quarternary: palette.dark.default.labelsQuarternary,
    },
    fills: {
      primary: palette.dark.default.fillsPrimary,
      secondary: palette.dark.default.fillsSecondary,
      tertiary: palette.dark.default.fillsTertiary,
      quarternary: palette.dark.default.fillsQuarternary,
    },
    separators: {
      opaque: palette.dark.default.separatorOpaque,
      nonOpaque: palette.dark.default.separatorNonOpaque,
    },
    accents: {
      primary: `hsl(${palette.dark.default.majorelleBlue})`,
      primary_a90: `hsl(${palette.dark.default.majorelleBlue} / 0.9)`,
      secondary: `hsl(${palette.dark.default.terraCotta})`,
      secondary_a90: `hsl(${palette.dark.default.terraCotta} / 0.9)`,
    },
  },
})

globalStyle('html', {
  boxSizing: 'border-box',
  backgroundColor: vars.colors.backgrounds.primary,
  height: '100%',
  lineHeight: '1.8',
  fontSize: '112.5%',
})

globalStyle('body', {
  margin: 0,
  height: '100%',
  display: 'flex',
  flexDirection: 'column',
})

globalStyle(
  `html,
  body,
  div,
  span,
  applet,
  object,
  iframe,
  h1,
  h2,
  h3,
  h4,
  h5,
  h6,
  p,
  blockquote,
  pre,
  a,
  abbr,
  acronym,
  address,
  big,
  cite,
  code,
  del,
  dfn,
  em,
  img,
  ins,
  kbd,
  q,
  s,
  samp,
  small,
  strike,
  strong,
  sub,
  sup,
  tt,
  var,
  b,
  u,
  i,
  center,
  dl,
  dt,
  dd,
  menu,
  ol,
  ul,
  li,
  fieldset,
  form,
  label,
  legend,
  table,
  caption,
  tbody,
  tfoot,
  thead,
  tr,
  th,
  td,
  article,
  aside,
  canvas,
  details,
  embed,
  figure,
  figcaption,
  footer,
  header,
  hgroup,
  main,
  menu,
  nav,
  output,
  ruby,
  section,
  summary,
  time,
  mark,
  audio,
  video`,
  {
    margin: '0',
    padding: '0',
    border: '0',
    verticalAlign: 'baseline',
  },
)

globalStyle('*, *::before, *::after', {
  boxSizing: 'inherit',
})
